server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/singh25mar/micro-config-service
          clone-on-start: true